logging:
    level:
        blog: WARN
        org: WARN
        org.hibernate.SQL: DEBUG
server:
    port: 8000
spring:
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        password: 1234567890
        url: jdbc:mysql://localhost:3306/softuni_mobilele_db?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: false
                show_sql: false
